### ISSUE TITLE
make 19th stable release

### ISSUE THREAD

**Issue by tsahara** [iij/mruby#153]
- x https://github.com/mruby/mruby/pull/2921 - refactoring
- x https://github.com/mruby/mruby/pull/2922 - refactoring
- x https://github.com/mruby/mruby/pull/2923 - refactoring
- x https://github.com/mruby/mruby/pull/2924 - improvement
- x https://github.com/mruby/mruby/pull/2925 - stable version does not have String#freeze
- x https://github.com/mruby/mruby/pull/2926 - not applicable
- x https://github.com/mruby/mruby/pull/2927 - feature change
- x https://github.com/mruby/mruby/pull/2928 - question
- x https://github.com/mruby/mruby/pull/2929 - documentation
- x https://github.com/mruby/mruby/pull/2930 - refactoring
- x https://github.com/mruby/mruby/pull/2931 - documentation
- x https://github.com/mruby/mruby/pull/2932 - not applicable
- x https://github.com/mruby/mruby/pull/2933 - works well on stable_1_0
- x https://github.com/mruby/mruby/pull/2934 - not applicable
- o https://github.com/mruby/mruby/pull/2935
  - https://github.com/iij/mruby/commit/59d3d5b5012f1ab45d4a51b4f06523b4675dad
- x https://github.com/mruby/mruby/pull/2936 - not applicable (instance_eval does not accept String)
- x https://github.com/mruby/mruby/pull/2937 - improvement
- x https://github.com/mruby/mruby/pull/2938 - documentation
- x https://github.com/mruby/mruby/pull/2939 - not applicable

**Comment by szepeviktor** [comment]
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item

This is the source:
```
- [x] @mentions, #refs, [links](), **formatting**, and <del>tags</del> are supported
- [x] list syntax is required (any unordered or ordered list supported)
- [x] this is a complete item
- [ ] this is an incomplete item
```

**Comment by tsahara** [comment]
@szepeviktor Thank you.  I'll try them next time.

**Comment by szepeviktor** [comment]
Here you are: https://github.com/iij/mruby/issues/153#issuecomment-138275575

**Comment by tsahara** [comment]
released https://github.com/iij/mruby/releases/tag/1.0-iij19
